name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./merge_csv
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy
    - name: Fmt check
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
